name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Stage
        run: echo "Running Linting to check code style and quality"

  code-coverage:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Code Coverage Stage
        run: echo "Calculating Code Coverage"

  security-scan:
    runs-on: ubuntu-latest
    needs: code-coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Security Scan Stage
        run: echo "Running Security Scan to detect vulnerabilities"

  build:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Stage
        run: echo "Running Build Stage"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Stage
        run: echo "Running Test Stage"

  sanity:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sanity Test Stage
        run: echo "Running Sanity Tests"

  regression:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Regression Test Stage
        run: echo "Running Regression Tests"

  uat:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: UAT Test Stage
        run: echo "Running UAT Tests"

  deploy:
    runs-on: ubuntu-latest
    needs: [test, sanity, regression, UAT]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Stage
        run: echo "Running Deploy Stage"